spring.application.name=backend

# Import local settings if they exist.
# application-local.properties is used for local development only and is ignored by Git.
spring.config.import=optional:application-local.properties

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable Open Session in View warning for cleaner API behaviour
spring.jpa.open-in-view=false
